#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Kitty terminal
rm -rfd ~/.config/kitty
ln -s ${BASEDIR}/config/kitty ~/.config/kitty

# Neovim 
rm -rfd ~/.config/nvim
ln -s ${BASEDIR}/config/nvim ~/.config/nvim

# i3
rm -rfd ~/.config/i3
ln -s ${BASEDIR}/config/i3 ~/.config/i3
